import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Providers } from '@/providers'
import { locales } from '@/i18n'
import {unstable_setRequestLocale} from 'next-intl/server';
import {NextIntlClientProvider, useMessages} from 'next-intl';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export default function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode,
  params: {locale: string}
}) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            {children}
            <Toaster toastOptions={{className: 'dark:!bg-neutral-800 dark:!text-white'}}/>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  )
}
